### PR TITLE
add react routing for home, about and login component

### PR DESCRIPTION
**Pull request by iAmmar7**

### CODE REVIEW

**Comment by osancus** [comment]
> sorry for the late review. Routing looks fine to me.

@aymenkhan092 have you seen @wakqasahmed comment on PR?

**Comment by aymenkhan092** [comment]
> > sorry for the late review. Routing looks fine to me.
> 
> @aymenkhan092 have you seen @wakqasahmed comment on PR? He requested some changes, and based on the one commit I just glanced at the changes are still not made.

yeah I have seen his comment. I am going to do my part so I will look into this too.

> > sorry for the late review. Routing looks fine to me.
> 
> @aymenkhan092 have you seen @wakqasahmed comment on PR? He requested some changes, and based on the one commit I just glanced at the changes are still not made.

**Comment by iAmmar7** [comment]
> Thanks for the effort @iAmmar7 you are very close for the pull request to be merged.
> 
> Didn't test the code by running but here is my feedback:
> 
> Good job,
> 
> 1. Header component main button "Issue Immunity Creds" links to Login route
> 2. React router is introduced (@iamsaeeddev may want to introduce Redux later, please discuss with him)
> 
> Changes required
> 
> 1. Default active tab should be home, not about. May be there can be a new component Home which will have Header, About and Footer components.
> 2. Single quotes are perfectly fine in import statements, is there any particular reason for adding double quotes?
> 3. ES6 allows you to omit semi colon (like python) so no need to add semi colon either if not required. Again any particular reason for adding it?
> 4. A lot of code is just reformatting the existing code, this causes confusion. Is it possible to keep the formatting as it is and just commit the actual contributed code?
> 
> In the end, really appreciate your contribution and happy learning as well.

@wakqasahmed Basically I am using **Prettier Code Formatter** and a lot of code formatting happened because I use `tabWidth: 2` and you have used `tabWidth: 4`. Same issue with the semi-colon and double-quotes. Everyone has their own preferences when it comes to code formatting. I like to use semi-colon because that enhance readability. Anyways, you should add a configuration file for code formatting, so that everyone works with the same configuration otherwise you are gonna label my every PR as a bad code :)

One more thing, there is no such Component as **Home** in your repository. So right now, application starts with **Issuer** component at the parent route i.e. `/`. From there we can use two more routes `/about` and `/login`. Adding or making Home (or any kind of) component is not related `react-router`. We can create or add a component and then we can add routing for this newly created component, that's not some kind of issue here. Let me know what do you think?

**Comment by wakqasahmed** [comment]
@iAmmar7 Thanks for the response. Here is my feedback:

1) Wow, I checked my VS Code and I already have Prettier installed (without my knowledge or I am getting old :D) but the difference i believe is I am using default configuration (and so will be most of the developers). Please try the default configuration and just take a moment to verify before sending another PR, it should be fine.

```
Tab Width: 2 (Default)
Tab Size: 4 (Default)
Single Quote: False (Default)
```
Having preference is fine but when it comes to open source (as i explained before) it doesn't scale, its better to stick to industry wide standard conventions.

2) Please create a card in the Kanban board for Home component. As the idea is to have 
Home page (having issue immunity cred button on top right side) -> Login page -> Issuer page

Then if you wish you can work on Home component that basically will be comprised of 
<Header />
<About />
<Footer />

OR someone else will work on Home component, but in that case routing needs to be modified by that person.

Let's have growth mindset. You got this bro!

**Comment by osancus** [comment]
> @iAmmar7 Thanks for the response. Here is my feedback:
> 
> 1. Wow, I checked my VS Code and I already have Prettier installed (without my knowledge or I am getting old :D) but the difference i believe is I am using default configuration (and so will be most of the developers). Please try the default configuration and just take a moment to verify before sending another PR, it should be fine.
> 
> ```
> Tab Width: 2 (Default)
> Tab Size: 4 (Default)
> Single Quote: False (Default)
> ```
> 
> Having preference is fine but when it comes to open source (as i explained before) it doesn't scale, its better to stick to industry wide standard conventions.
> 
> 2. Please create a card in the Kanban board for Home component. As the idea is to have
>    Home page (having issue immunity cred button on top right side) -> Login page -> Issuer page
> 
> Then if you wish you can work on Home component that basically will be comprised of
> <Header />
> <About />
> <Footer />
> 
> OR someone else will work on Home component, but in that case routing needs to be modified by that person.
> 
> Let's have growth mindset. You got this bro!

@wakqasahmed comment #2 is not clear to @iAmmar7, can you please take some to explain it further.

**Comment by iAmmar7** [comment]
One more thing is confusing. @wakqasahmed in your first comment when you asked for changes, you wrote in your second point that you want to have single quotes in import statements. But then in your last comment you wrote you have default setting of `Single Quotes: False`. That's confusing. Don't you think this should be `Single Quotes: True` if we want to work with Single Quotes.

**Comment by wakqasahmed** [comment]
@iAmmar7 

1) In simple words, I think for now there should be atleast the following pages.
Home Page /home
About Page /about
FAQ Page /faq
Login Page /login
Issuer Page /issuer

2) `Single Quotes: False` probably means "Do not convert double quotes into single quotes upon saving". 

But forget about the individual settings. As suggested by @osancus everyone can simply just use standardJS library. Whatever formatting goes with default standardJS, everyone would have the same. Have you already installed this? https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs

**Comment by iAmmar7** [comment]
A LOT OF CHANGES ALERT

1. Please keep in mind I have added `.prettierrc` . So even if I didn't create a file but edit one of the existing file, it will show a lot of code reformatting the existing code. But from now on, this will not happen because everyone will follow the same configuration.
2. Moved all components from `/src` to `/src/components` directory, and then within their respective folders.
3. Changed header component and added hard coded navbar items in `sticky-header` (before that it was coming from jQuery and it was not working).
4. Added CSS in property in `custome-style.css` for smooth scrolling (theme is using jQuery for smooth scrolling which is of course also not working).
5. Moved all png files from `/src` to `/src/images` folder.
6. Added 3 dummy components. `Home` , `Faq` ,`HowItWorks` . These components should be created in a separate PR.
7. Added routing from `root -> login -> issuer` .
8. Also added a package of `react-router-hash-link` for on click scrolling.
9. Edited routing in `App.js` according to new components.

**Pull request merged**
